server:
  port: 8092
spring:
  application:
    name: fps-bus-ms-venar-ravash
  profiles:
    active: ${PROFILE:dev}
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
logging:
  config: classpath:logging/logback.xml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
validation-custom:
  app-id-flag: 0
  app-id: ZnBzLWJ1cy1tcy12ZW5hci1yYXZhc2g=
